name: Basic Build Workflow

on:
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rosdistro: [humble, iron, jazzy, rolling]
      fail-fast: false
    container:
      image: ros:${{ matrix.rosdistro }}-ros-base
    steps:
      - name: Build Environment
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: ${{ matrix.rosdistro }}
      - name: Run Tests
        uses: ros-tooling/action-ros-ci@v0.3
        with:
          package-name: |
            velodyne
            velodyne_driver
            velodyne_laserscan
            velodyne_msgs
            velodyne_pointcloud
          target-ros2-distro: ${{ matrix.rosdistro }}
      - name: Upload logs
        uses: actions/upload-artifact@v4
        with:
          name: colcon-logs-${{ matrix.rosdistro }}
          path: ros_ws/log
        if: always()
